<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Helium')->setSeparator(' - ')->setAutoEscape(false) ?>

        <!-- Core CSS file -->
        <link rel="stylesheet" href="/photoswipe/photoswipe.css"> 

        <!-- Skin CSS file (styling of UI - buttons, caption, etc.)
             In the folder of skin CSS file there are also:
             - .png and .svg icons sprite, 
             - preloader.gif (for browsers that do not support CSS animations) -->
        <link rel="stylesheet" href="/photoswipe/default-skin/default-skin.css"> 

        <!-- Core JS file -->
        <script src="/photoswipe/photoswipe.min.js"></script> 

        <!-- UI JS file -->
        <script src="/photoswipe/photoswipe-ui-default.min.js"></script> 
        
        <style>
            .pswp__container{
                transition:.5s ease-in-out all;
            }
        </style>
        
    </head>
    <body>
        
        <div class="container">
            <?= $this->content; ?>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
