<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Helium')->setSeparator(' - ')->setAutoEscape(false) ?>

        <!-- CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="/photoswipe/photoswipe.css"> 
        <link rel="stylesheet" href="/photoswipe/default-skin/default-skin.css"> 
        <style>
            .pswp__container{
                transition:.5s ease-in-out all;
            }
        </style>
        
        <!-- JS -->
        <script src="/photoswipe/photoswipe.min.js"></script>
        <script src="/photoswipe/photoswipe-ui-default.min.js"></script>
        <?php echo $this->headScript()->prependFile('https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js')
                                      ->prependFile('/js/jquery-1.11.3.min.js') ?>
        
        
        
    </head>
    <body>
        
        <div class="container">
            <?= $this->content; ?>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
