<h1>Your Galleries</h1>
<a class="btn btn-primary" href="<?php echo $this->url('helium/default', array('controller' => 'gallery', 'action' => 'add')); ?>">New Gallery</a>
<h2>Galleries</h2>

<ul class="nav nav-tabs">
  <li role="presentation" class="active"><a href="#">Home</a></li>
  <li role="presentation"><a href="#">Galleries</a></li>
  <li role="presentation"><a href="#">Tags</a></li>
</ul>

<br><br><br>

<table class="table">
    <thead>
        
    </thead>
    <tbody>
    <?php foreach($this->galleries as $gallery): ?>
    <tr>
        <td>
            <h4 class="text-primary"><?php echo $gallery->getName(); ?></h4>
            <span class="small">Updated 28th July 2016</span>
        </td>
        <td>
            <span class="label label-default"><?php echo $gallery->getVisibility(); ?></span>
        </td>
    </tr>
    <?php endforeach; ?>
    <tbody>
</table>
