<div class="jumbotron">
    <h1>Welcome to <span class="zf-green">Helium</span></h1>

    <p>
        Congratulations! You have successfully installed the
        <a href="https://github.com/srayner/helium" target="_blank">Helium Application</a>.
        This project is currently a work in progress, so check github for latest version.
        This skeleton can serve as a simple starting point for you to begin
        building your own photo gallery application.
    </p>

    <p><a class="btn btn-success btn-lg" href="https://github.com/zendframework/zendframework" target="_blank">Fork Zend Framework on GitHub &raquo;</a></p>
</div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Galleries</h3>
            </div>
            <div class="panel-body">
                <p>
                    Photo galleries can be created. You can then add photographs to a gallery and
                    decide if you want the gallery to be public or private.
                </p>

                <p><a class="btn btn-success pull-right" href="/application/gallery" target="_blank">Example Gallery &raquo;</a></p>
            </div>
        </div>
    </div>

    
</div>
